### ISSUE TITLE
handle nonce errors better

### ISSUE THREAD

**Issue by utdrmac** [taniman/gunbotproxycommunity#24]
Starting to get these every time my gunbot 332 tries to make a buy/sale. Not using this API key anywhere else. Seems that the proxy could parse/read the "must be greater than" nonce and reset itself.

```
Aug 03, 2017 3:56:54 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is nl.komtek.gpi.utils.ProxyHandledException: nonce error: {"error":"Nonce must be greater than 150145253591700000. You provided 15017758143230000."}] with root cause
nl.komtek.gpi.utils.ProxyHandledException: nonce error: {"error":"Nonce must be greater than 150145253591700000. You provided 15017758143230000."}
```

**Comment by utdrmac** [comment]
Strange error anyways. 15014... vs provided 15017...  clearly the provided nonce is greater.

**Comment by taniman** [comment]
150145253591700000
15017758143230000

put them on top of each other you see the provided one is not greater. 

The proxy is using an external library to perform the apiCalls. But I will be making some changes to the library to allow better nonce error handling
