### ISSUE TITLE
feature request: Keep BTC-Balance

### ISSUE THREAD

**Issue by rube-de** [taniman/gunbotproxycommunity#45]
It would be nice to have a feature that lets you decide how many BTC you want to keep in portfolio and don't give the GB for trading. This could be handy if you want to withdraw BTC on a regular basis.

e.g.: I configure keep: 0,2 BTC and the bot only trades with BTC above the 0,2 BTC level

see also:
https://gunthy.org/index.php/topic,1054.0.html

**Comment by taniman** [comment]
Did the user recieve the message after when balacne reacher 0.009?
You are not allowed to buy. Buy will exceed min buy balance?
