### ISSUE TITLE
Outstanding Order

### ISSUE THREAD

**Issue by vbootstrap** [taniman/gunbotproxycommunity#5]
Outstanding orders are not being correctly reported to the bot.

**Comment by taniman** [comment]
With outstanding order you mean open orders right? What exactly is not reported correctly? are you on 0.9.1?

**Comment by vbootstrap** [comment]
Yeah open orders.  I am running 0.9.1

**Comment by taniman** [comment]
hmmm. Did some tests yesterday, everything seemed fine. I created order in polo and after a few seconds the bot was already telling me that there were order. 

What problem are you noticing. And is it still happening?

**Comment by vbootstrap** [comment]
I'll keep watching and update.

**Comment by vbootstrap** [comment]
ok what is going on is it takes 3 polling cycles of the bot after the buy is sent for the open order indicator to show up.

**Comment by vbootstrap** [comment]
then if the order is still open after 3 more cycles the order is cancelled.

**Comment by taniman** [comment]
The cancelling is being done by GB. But I guess I may have found a probable cause for the order taking some time to appear
