### ISSUE TITLE
comma/punctuation error

### ISSUE THREAD

**Issue by gmjosund** [taniman/gunbotproxycommunity#62]
Hey Elroy,

Can you force punctuation on profit column, or better all column so the javascript works with negative/positive values.

Thanks

dj_crypto

**Comment by YoJeff** [comment]
Just kill the commas.   Something like this:

```
         var $cells = document.getElementsByTagName('td'), $negative, $i;
         for ($i = 0; $i < $cells.length; $i++) {
            const $value = $cells[$i].innerHTML.replace(',','')
            if ($cells[$i].className === 'negative' && !isNaN($value)) {
               $negative = (1 * $value) < 0;
               $cells[$i].style.backgroundColor = $negative ? '#b22222' : '#00804f';
               $cells[$i].style.color           = $negative ? '#ffffff' : '#ffffff';
            }
         }
```

**Comment by gmjosund** [comment]
Yes that works good too 👍 Thanks Jeff

**Comment by scoutband** [comment]
I would do it even more captivating:
from +0.01 to +99.99 green
from -0.00 to +0.00 neutral
from -0.01 to -3.99 yellow
from -4.00 to -9.99 orange
from -10.00 to -99.99 red

**Comment by YoJeff** [comment]
Here is a little snippet I have used elsewhere that will show degrees or red and green depending....


```
export const percentColor = (percent) => {
  const bgColorScale = (Math.abs(percent * 100) / 10) + 0.2  
  return (percent > 0) ? `rgba(129, 199, 132,${bgColorScale}) ` : `rgba(229, 115, 115,${bgColorScale})`
}
```

**Comment by taniman** [comment]
I will fix the comma and punctuation. degrees of colors will have to wait a bit.
