### ISSUE TITLE
Trailing buys

### ISSUE THREAD

**Issue by YoJeff** [taniman/gunbotproxycommunity#64]
The trailing stops for sells work great.   How about doing something similar on the buy side?

```
ALL_buy_strategy = GAIN
ALL_buy_value = 3.0
ALL_buy_trailing_stop = 1.0
```

**Comment by taniman** [comment]
A little more explanation. What is GAIN value of 3? Is that like GB that looks at EMA values? Because currently my GAIN does not do EMA stuff. Nor should it. GAIN is GAIN. LOSS is LOSS

**Comment by scoutband** [comment]
An alternative maybe:
-x% when negative LOWBB is reached... start to follow de dump based on ALL_buy_value and ALL_buy_trailing_stop

**Comment by YoJeff** [comment]
Yeah, I was thinking of GAIN in GB terms.   % from EMA with trailing buy.

**Comment by YoJeff** [comment]
Ok after sleeping on this....   I think I'm too attached to EMA's.   %BB approximates the same thing.

So trailing buy would still be great for BB based entries -- just treat it the same as exits.    BB strat specifies the trigger, then trail for the actual buy.    Hopefully this can prevent buying at the top of dumps when it rides the lower BB all the way down to some degree.

**Comment by scoutband** [comment]
Exactly what I meant in my comment ;)

**Comment by lenardbang** [comment]
this would be SOOOO great, the way trailing sell works now is awesome! similiar traling for buy on drops from initial buy threshold would be golden
